name: "Pull New Fonts"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0"
jobs:
  update_fonts:
    runs-on: macos-latest

    steps:
      - name: FindLatestTag
        uses: oprypin/find-latest-tag@v1.0.4
        with:
          repository: "FortAwesome/Font-Awesome"
          releases-only: true

      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          clean: true
      
      - name: run
        run: |
          cd FortAwesome/Font-Awesome/
          git fetch origin
          git checkout 5.13.0
          cp -f ./otfs/*.otf ../../FontAwesome
          cd ../../
          ./codegen.swift
          git commit -am "Update font version to 5.13.0"
          
          bundle install
          bundle exec fastlane release version:5.13.0
